#!/usr/bin/env bash

set -e
set -x

hostname
whoami
groups
pwd
ls

ls exports


# Convention:
#  firmware-<version>.<platform>.bin
# Example:
#  firmware-3.1.1.esp32.bin

export EXPO=/var/lib/main4ino/httpexposed/sleepino

function export_firmware_for_platform() {
  local platform=$1

  echo "Exporting files for $platform..."

  find . -name 'firmware-*.'$platform'.bin' > files.list

  for f in `cat files.list`
  do
    echo "Moving $f..."
    mv -f $f $EXPO
  done

}

export_firmware_for_platform esp8266
export_firmware_for_platform esp32
